//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaiveBayesClassifier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NaiveBayesClassifier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spam	Urgent UR awarded a complimentary trip to EuroDisinc Trav, Aco&amp;Entry41 Or £1000. To claim txt DIS to 87121 18+6*£1.50(moreFrmMob. ShrAcomOrSglSuplt)10, LS1 3AJ
        ///spam	&quot;Welcome to UK-mobile-date this msg is FREE giving you free calling to 08719839835. Future mgs billed at 150p daily. To cancel send &quot;&quot;go stop&quot;&quot; to 89123&quot;
        ///spam	3. You have received your mobile content. Enjoy
        ///spam	Want explicit SEX in 30 secs? Ring 02073162414 now! Costs 20p/min
        ///spam	Latest Nokia Mobile or iPOD MP3 Player +£400 proze GUAR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SMSSpamTest {
            get {
                return ResourceManager.GetString("SMSSpamTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ham	Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...
        ///ham	Ok lar... Joking wif u oni...
        ///spam	Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&amp;C&apos;s apply 08452810075over18&apos;s
        ///ham	U dun say so early hor... U c already then say...
        ///ham	Nah I don&apos;t think he goes to usf, he lives around here though
        ///spam	FreeMsg Hey there darling it&apos;s been 3 week&apos;s now and no word back! I&apos;d  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SMSSpamTrain {
            get {
                return ResourceManager.GetString("SMSSpamTrain", resourceCulture);
            }
        }
    }
}
